# Generated by Django 2.1.5 on 2019-02-03 01:59

import analyzer.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator', models.CharField(max_length=256)),
                ('event_id', models.IntegerField()),
                ('event_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('analysis_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(verbose_name='date created')),
                ('status', models.CharField(choices=[(analyzer.models.AnalysisStatus('Upload in progress'), 'Upload in progress'), (analyzer.models.AnalysisStatus('Extraction of indicator'), 'Extraction of indicator'), (analyzer.models.AnalysisStatus('Research of indicators in the database'), 'Research of indicators in the database'), (analyzer.models.AnalysisStatus('Error'), 'Error'), (analyzer.models.AnalysisStatus('Done'), 'Done')], max_length=10)),
                ('result', models.CharField(choices=[(analyzer.models.AnalysisResult('Nothing malicious found'), 'Nothing malicious found'), (analyzer.models.AnalysisResult('Malicious indicators found'), 'Malicious indicators found'), (analyzer.models.AnalysisResult('Error during analysis'), 'Error during analysis')], max_length=10)),
                ('ip', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='alert',
            name='analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.Analysis'),
        ),
    ]
